language: cpp

sudo: required

compiler:
- g++

os:
- linux

before_script:
- sudo echo Build started on `date`
- sudo apt-get update -y
- sudo apt-get install -y software-properties-common 
- sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
- sudo apt-get update -y
- sudo apt-get install -y cmake libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev

script: 
- mkdir build
- cd build
- cmake ..
- make -j4

branches:
  only:
  - master
